### PR TITLE
Moved idea.properties definition to manifest

### PR DESCRIPTION
**Pull request by rtmor**
@x80486 

I encountered an error while trying to install both the build and from source:

```
F: Running /app/bin/apply_extra
/app/bin/apply_extra: line 7: idea.properties: No such file or directory
Error: While trying to apply extra data: apply_extra script failed, exit status 256
error: Failed to install com.jetbrains.DataGrip: While trying to apply extra data: apply_extra script failed, exit status 256
```

I was able to get around it by moving the idea.properties definition to the manifest. Maybe you have a more elegant solution or could explain why it didn't install correctly the first time.

### CODE REVIEW

**Comment by x80486** [comment]
Great! Thanks for finding that inconsistency :bowing_man:

I'll integrate your changes on the other branch that I have, if you don't mind.

**Comment by rtmor** [comment]
Yes, thank you! I apologize for creating a new PR -- wasn't able to push to the existing PR.

It does look like the new build failed when `- tee <idea.properties --append ${FLATPAK_DEST}/bin/idea.properties` was changed to `- tee <idea.properties --append datagrip/bin/idea.properties`. Perhaps the append option requires an absolute path? :confused:

**Comment by x80486** [comment]
I think what you had was right, but as far as I know, `FLATPAK_DEST` resolves to `/app`. I'll have to check when `DataGrip` is installed that it's actually copying the file to the correct location.

**Comment by x80486** [comment]
> Yeah, you're right. It's resolving to `/app`. I went ahead and just expanded it in my PR and got a good build.
> 
> ```
> - tee < idea.properties --append /app/bin/idea.properties
> ```

I think the resultant file will only contain what's in `idea.properties` because there shouldn't be anything under `/app/bin/idea.properties` — and what's desired is to merge `idea.properties` with the other `idea.properties` that's being released with `DataDrip`.

Doing it this way, you still don't have access to that file, but if I place the `tee` command inside `apply_extra.sh`, then I don't have access to the `idea.properties` I'm trying to merge.

**Comment by rtmor** [comment]
I see. You're absolutely right - it is overwriting instead of appending. I'll take another look at it tonight.

Thanks :smiley:

**Pull request closed without merging**
