### PR TITLE
Remove zypak-wrapper and set property to avoid issues with Chrome's sandboxing mechanism

### PR DESCRIPTION
**Pull request by x80486**

### CODE REVIEW

**Comment by x80486** [comment]
@rtmor, if you have a change, can you try this build?

**Comment by x80486** [comment]
OK. Great! There are several reports that `zypak-wrapper` is causing some unexpected behavior, so I think this setting is more straightforward, and targets exactly the issue, as reported in `IDEA`s `YouTrack`.

Let me know how it went on your side.

**Comment by x80486** [comment]
Tried this one and it's working, though I can't use `DataGrip` anymore. It's asking me to create an account even for the trial period :rage:

**Comment by rtmor** [comment]
So far so good.

Maybe try removing your previous application data to let it repopulate on load.

`mv ${HOME}/.var/app/com.jetbrains.DataGrip{,.bk}`

**Comment by x80486** [comment]
Thanks, @rtmor! I'll see if I can check the content of `/app/extra/DataGrip/bin/application.properties` when the application is running, and if everything is fine I'll merge this one.

**Comment by x80486** [comment]
@rtmor, I did finally went in a slightly different route. I ended up using one of the built-in mechanism to override the config values. It requires less back and forth with the commands.

Let me know if you have any issues.

**Comment by rtmor** [comment]
Much nicer solution! Everything is working smooth over here :+1:

**Pull request merged**
